title: Senne Heeren
logo: /imgs/headshot.jpeg
description: Institute of Tropical Medicine Antwerp, Belgium <br /> KU Leuven, Belgium <br /> University of Antwerp, Belgium <br /> Orcid-ID: 0000-0002-5786-258X
linkedin_username: senne-h-8183b51b0
#show_downloads: true
theme: jekyll-theme-minimal
