title: Senne Heeren
logo: /imgs/headshot.jpeg
description: Institute of Tropical Medicine Antwerp, Belgium <br /> KU Leuven, Belgium <br /> University of Antwerp, Belgium
description: KU Leuven, Belgium 
description: [Orcid](https://orcid.org/0000-0002-5786-258X)
#show_downloads: true
theme: jekyll-theme-minimal
