title: Senne Heeren
logo: /imgs/imgs/headshot.jpeg
description: Affiliations, Molecular Parasitology, Institute of Tropical Medicine Antwerp, Belgium; Rega Institute for Medical Research, KU Leuven, Belgium, Dpt. of Pharmaceutical, Veterinairy and Biomedical Sciences, University of Antwerp, Belgium
#show_downloads: true
theme: jekyll-theme-minimal
